export const sampleMentorsData = [
    {
        id: 1,
        name: "John Doe",
        username: "johndoe123",
        dob: "1990-05-15",
        email: "johndoe@example.com",
        contactNumber: "+1234567890",
        photo: "john_doe_photo.jpg",
        about: "Experienced full-stack web developer with a passion for teaching.",
        address: "123 Elm Street, Springfield, IL, USA",
        education: "B.Tech in Computer Science, University of Springfield",
        assignedCourses: [
            { courseId: 1, courseName: "Full Stack Web Development" },
        ],
        timeAvailability: {
            monday: "9 AM - 5 PM",
            tuesday: "9 AM - 5 PM",
            wednesday: "9 AM - 5 PM",
            thursday: "9 AM - 5 PM",
            friday: "9 AM - 5 PM",
        },
        password: "securepassword123",
    },
    {
        id: 2,
        name: "Jane Smith",
        username: "janesmith456",
        dob: "1985-07-25",
        email: "janesmith@example.com",
        contactNumber: "+1987654321",
        photo: "jane_smith_photo.jpg",
        about: "Digital marketing expert with specialization in SEO and SEM.",
        address: "456 Oak Avenue, San Francisco, CA, USA",
        education: "MBA in Marketing, Stanford University",
        assignedCourses: [
            { courseId: 2, courseName: "Digital Marketing Mastery" },
        ],
        timeAvailability: {
            monday: "10 AM - 4 PM",
            wednesday: "10 AM - 4 PM",
            friday: "10 AM - 4 PM",
        },
        password: "marketingexpert456",
    },
    {
        id: 3,
        name: "Alice Brown",
        username: "alicebrown789",
        dob: "1992-12-01",
        email: "alicebrown@example.com",
        contactNumber: "+1122334455",
        photo: "alice_brown_photo.jpg",
        about: "Data scientist with expertise in machine learning and AI technologies.",
        address: "789 Pine Road, New York, NY, USA",
        education: "M.Sc. in Data Science, University of New York",
        assignedCourses: [
            { courseId: 3, courseName: "Data Science Essentials" },
        ],
        timeAvailability: {
            monday: "8 AM - 4 PM",
            tuesday: "8 AM - 4 PM",
            thursday: "8 AM - 4 PM",
            friday: "8 AM - 4 PM",
        },
        password: "datascientist789",
    },
];
