import { MentorProps } from "@/Types/Mentor.type";

export const sampleMentorsData: MentorProps[] = [
    {
        id: 1,
        name: "John Doe",
        username: "johndoe123",
        dob: "1990-05-15",
        email: "johndoe@example.com",
        contactNumber: "+1234567890",
        photo: "john_doe_photo.jpg",
        about: "Experienced full-stack web developer with a passion for teaching.",
        address: "123 Elm Street, Springfield, IL, USA",
        education: "B.Tech in Computer Science, University of Springfield",
        assignedCourses: [
            {
                id: 1,
                courseName: "Full Stack Web Development",
                category: { _id: "12", name: "New" },
                subcategory: { _id: "123", categoryId: "12", name: "Frontend Development" },
                description: "Learn to build full-stack web applications using modern technologies.",
                duration: "6 months",
                mentorAssigned: "John Doe",
                managerAssigned: "Alice Manager",
                batchesAvailable: ["Batch A", "Batch B"],
                promoCodes: [
                    {
                        code: "FULLSTACK10",
                        discountPercentage: 10,
                        expiryDate: "2025-12-31",
                        applicableTo: "Full Stack Web Development",
                        usageLimit: "Unlimited",
                        category: { _id: "12", name: "New" },
                    },
                ],
                price: 500,
            },
        ],
        timeAvailability: "9 AM - 5 PM",
        password: "securepassword123",
    },
    {
        id: 2,
        name: "Jane Smith",
        username: "janesmith456",
        dob: "1985-07-25",
        email: "janesmith@example.com",
        contactNumber: "+1987654321",
        photo: "jane_smith_photo.jpg",
        about: "Digital marketing expert with specialization in SEO and SEM.",
        address: "456 Oak Avenue, San Francisco, CA, USA",
        education: "MBA in Marketing, Stanford University",
        assignedCourses: [
            {
                id: 2,
                courseName: "Digital Marketing Mastery",
                category: { _id: "13", name: "Marketing" },
                subcategory: { _id: "131", categoryId: "13", name: "SEO" },
                description: "Master the art of digital marketing, including SEO and SEM techniques.",
                duration: "4 months",
                mentorAssigned: "Jane Smith",
                managerAssigned: "Bob Manager",
                batchesAvailable: ["Batch C", "Batch D"],
                promoCodes: [
                    {
                        code: "MARKETING20",
                        discountPercentage: 20,
                        expiryDate: "2025-12-31",
                        applicableTo: "Digital Marketing Mastery",
                        usageLimit: "50",
                        category: { _id: "13", name: "Marketing" },
                    },
                ],
                price: 400,
            },
        ],
        timeAvailability: "10 AM - 4 PM",
        password: "marketingexpert456",
    },
    {
        id: 3,
        name: "Alice Brown",
        username: "alicebrown789",
        dob: "1992-12-01",
        email: "alicebrown@example.com",
        contactNumber: "+1122334455",
        photo: "alice_brown_photo.jpg",
        about: "Data scientist with expertise in machine learning and AI technologies.",
        address: "789 Pine Road, New York, NY, USA",
        education: "M.Sc. in Data Science, University of New York",
        assignedCourses: [
            {
                id: 3,
                courseName: "Data Science Essentials",
                category: { _id: "14", name: "Data Science" },
                subcategory: { _id: "141", categoryId: "14", name: "Machine Learning" },
                description: "Learn the fundamentals of data science and machine learning.",
                duration: "5 months",
                mentorAssigned: "Alice Brown",
                managerAssigned: "Charlie Manager",
                batchesAvailable: ["Batch E", "Batch F"],
                promoCodes: [
                    {
                        code: "DATASCI10",
                        discountPercentage: 10,
                        expiryDate: "2025-12-31",
                        applicableTo: "Data Science Essentials",
                        usageLimit: "Unlimited",
                        category: { _id: "14", name: "Data Science" },
                    },
                ],
                price: 600,
            },
        ],
        timeAvailability: "8 AM - 4 PM",
        password: "datascientist789",
    },
    {
        id: 4,
        name: "Michael Johnson",
        username: "mikejohnson321",
        dob: "1988-09-10",
        email: "michaelj@example.com",
        contactNumber: "+9876543210",
        photo: "michael_johnson_photo.jpg",
        about: "Software engineer with expertise in DevOps and cloud computing.",
        address: "321 Maple Drive, Austin, TX, USA",
        education: "B.Sc. in Information Technology, University of Texas",
        assignedCourses: [
            {
                id: 4,
                courseName: "DevOps Masterclass",
                category: { _id: "15", name: "DevOps" },
                subcategory: { _id: "151", categoryId: "15", name: "Cloud Computing" },
                description: "Learn to implement DevOps practices and manage cloud infrastructures.",
                duration: "3 months",
                mentorAssigned: "Michael Johnson",
                managerAssigned: "Diana Manager",
                batchesAvailable: ["Batch G", "Batch H"],
                promoCodes: [
                    {
                        code: "DEVOPS15",
                        discountPercentage: 15,
                        expiryDate: "2025-12-31",
                        applicableTo: "DevOps Masterclass",
                        usageLimit: "100",
                        category: { _id: "15", name: "DevOps" },
                    },
                ],
                price: 700,
            },
        ],
        timeAvailability: "11 AM - 6 PM",
        password: "devopsguru321",
    },
    {
        id: 5,
        name: "Emily Davis",
        username: "emilydavis123",
        dob: "1995-03-20",
        email: "emilyd@example.com",
        contactNumber: "+1230987654",
        photo: "emily_davis_photo.jpg",
        about: "UI/UX designer passionate about creating intuitive and user-friendly interfaces.",
        address: "567 Birch Lane, Los Angeles, CA, USA",
        education: "Diploma in UI/UX Design, California Design Institute",
        assignedCourses: [
            {
                id: 5,
                courseName: "UI/UX Design Fundamentals",
                category: { _id: "16", name: "Design" },
                subcategory: { _id: "161", categoryId: "16", name: "User Experience" },
                description: "Learn the principles of UI/UX design and create stunning user interfaces.",
                duration: "4 months",
                mentorAssigned: "Emily Davis",
                managerAssigned: "Sophia Manager",
                batchesAvailable: ["Batch I", "Batch J"],
                promoCodes: [
                    {
                        code: "UXDESIGN10",
                        discountPercentage: 10,
                        expiryDate: "2025-12-31",
                        applicableTo: "UI/UX Design Fundamentals",
                        usageLimit: "Unlimited",
                        category: { _id: "16", name: "Design" },
                    },
                ],
                price: 300,
            },
        ],
        timeAvailability: "9 AM - 3 PM",
        password: "designwizard123",
    },
];