import { EmployerProps } from "@/Types/Employer.type";

export const sampleEmployersData: EmployerProps[] = [
    {
        id: 1,
        name: "Tech Innovators Inc.",
        email: "contact@techinnovators.com",
        password: "encryptedpassword123",
        contactNumber: "+1234567890",
        photo: "tech_innovators_logo.jpg",
        industry: "Technology",
        address: "123 Silicon Valley, San Francisco, CA, USA",
        companySize: "51-200 Employees",
    },
    {
        id: 2,
        name: "Green Earth Solutions",
        email: "info@greenearth.com",
        password: "securepassword456",
        contactNumber: "+1987654321",
        photo: "green_earth_logo.jpg",
        industry: "Environmental Services",
        address: "456 Eco Drive, Austin, TX, USA",
        companySize: "11-50 Employees",
    },
    {
        id: 3,
        name: "Healthcare Horizons",
        email: "hr@healthcarehorizons.com",
        password: "healthcarepass789",
        contactNumber: "+1122334455",
        photo: "healthcare_horizons_logo.jpg",
        industry: "Healthcare",
        address: "789 Wellness Lane, New York, NY, USA",
        companySize: "201-500 Employees",
    },
    {
        id: 4,
        name: "Finance Forward",
        email: "admin@financeforward.com",
        password: "finpass001",
        contactNumber: "+14155552671",
        photo: "finance_forward_logo.jpg",
        industry: "Finance",
        address: "987 Wall Street, New York, NY, USA",
        companySize: "10,001+ Employees",
    },
    {
        id: 5,
        name: "Creative Studios",
        email: "hello@creativestudios.com",
        password: "designsecure2025",
        contactNumber: "+16504432110",
        photo: "creative_studios_logo.jpg",
        industry: "Design",
        address: "321 Art Avenue, Los Angeles, CA, USA",
        companySize: "1-10 Employees",
    },
];
