export const sampleStudentsData = [
    {
        id: 1,
        name: "John Doe",
        dob: "1990-05-15",
        email: "johndoe@example.com",
        contactNumber: "+1234567890",
        photo: "john_doe_photo.jpg",
        guardianName: "Michael Doe",
        address: "123 Elm Street, Springfield, IL, USA",
        education: "B.Tech in Computer Science, University of Springfield",
        coursesEnrolled: ["Full Stack Web Development", "ReactJS Advanced"],
        interests: ["Coding", "Teaching", "Open Source"],
        languagesPreferred: ["English", "Spanish"],
        wannaBe: "Full-Stack Developer",
        experience: "5 years",
        batch: "Batch A",
        roadmapEnrolled: "Full Stack Development",
        password: "securepassword123",
        resume: "https://example.com/john_doe_resume.pdf",
    },
    {
        id: 2,
        name: "Jane Smith",
        dob: "1985-07-25",
        email: "janesmith@example.com",
        contactNumber: "+1987654321",
        photo: "jane_smith_photo.jpg",
        guardianName: "Laura Smith",
        address: "456 Oak Avenue, San Francisco, CA, USA",
        education: "MBA in Marketing, Stanford University",
        coursesEnrolled: ["Digital Marketing Mastery", "SEO Basics"],
        interests: ["Marketing", "SEO", "Content Creation"],
        languagesPreferred: ["English", "French"],
        wannaBe: "Digital Marketing Specialist",
        experience: "8 years",
        batch: "Batch B",
        roadmapEnrolled: "Marketing Strategy",
        password: "marketingexpert456",
        resume: "https://example.com/jane_smith_resume.pdf",
    },
    {
        id: 3,
        name: "Alice Brown",
        dob: "1992-12-01",
        email: "alicebrown@example.com",
        contactNumber: "+1122334455",
        photo: "alice_brown_photo.jpg",
        guardianName: "David Brown",
        address: "789 Pine Road, New York, NY, USA",
        education: "M.Sc. in Data Science, University of New York",
        coursesEnrolled: ["Data Science Essentials", "AI for Beginners"],
        interests: ["Machine Learning", "AI", "Data Visualization"],
        languagesPreferred: ["English"],
        wannaBe: "Data Scientist",
        experience: "3 years",
        batch: "Batch C",
        roadmapEnrolled: "Data Science",
        password: "datascientist789",
        resume: "https://example.com/alice_brown_resume.pdf",
    },
];
